name: Test Topic 1
on: 
  push:
   
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: |
        git config --local user.email "unclecode@kplay.team"
        git config --local user.name "kportal-hub"
        git checkout master
        echo "hiz" > a.txt
        git add --all
        git commit -m "test push with action"
        git push https://kportal-hub:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}} master
        echo "done"
     
